# Default values for room-management.
replicaCount: 3
revisionHistoryLimit: 3

image:
  repository: ghcr.io/mingleflix/roommanagement
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

containerPort: 3000

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

imagePullSecrets:
  - name: ghcr-io-secret

env:
  REDIS_HOST: room-management-redis-master

redis:
  architecture: standalone
  auth:
    enabled: false
  primary:
    persistence:
      enabled: false