# Default values for room-management.
replicaCount: 2
revisionHistoryLimit: 3

image:
  repository: ghcr.io/mingleflix/roommanagement
  pullPolicy: IfNotPresent
  tag: latest

service:
  type: ClusterIP
  port: 80
  targetPort: 3001

containerPort: 3001

resources:
  limits:
    cpu: 100m
    memory: 128Mi
  requests:
    cpu: 100m
    memory: 128Mi

imagePullSecrets:
  - name: ghcr-io-secret

jwtSecret:
  name: jwt-secret
  key: JWT_SECRET

env:
  REDIS_HOST: room-management-redis-master

redis:
  architecture: standalone
  auth:
    enabled: false
  primary:
    persistence:
      enabled: false